### ISSUE TITLE
update the sponsorship team page

### ISSUE THREAD

**Issue by ghwood** [ghwood/www.ietf.org_content#14]
This seems in need of updating

https://www.ietf.org/about/donors/ietf-sponsorship-team/

**Comment by LeeBerkeleyShaw** [comment]
I would think a page like this should come off of the Meeting Sponsorship Page, not the Financial Supporters page. But why don't we just put this in a blue Call to Action box at the bottom of the Meeting Sponsorship page with a link to that email, and then we don't need this page at all? Would that work?

**Comment by ghwood** [comment]
Done.
