### ISSUE TITLE
Link for Credit Card Payment is broken

### ISSUE THREAD

**Issue by LeeBerkeleyShaw** [ghwood/www.ietf.org_content#16]
On the Support Us page, when you get to the HOW to make a donation, the first link for the online donation portal gets a 404 error for me. It should go to the donation portal for "supporters", not endowment.

**Comment by ghwood** [comment]
this is fixed and I've added a redirect to catch any other instances of the legacy link. 

As a general point, I thought we preferred pointing folks to the endowment because of matching?

**Comment by LeeBerkeleyShaw** [comment]
Normally, yes, I want to point people to endowment, but this right under operating support, and so it seems natural that if you want to give, but not to the endowment, you need a place, and this is it. It's not the portal I'll emphasize in my appeal, but I do think we need to have it as an option. In a perfect world, there would be one portal, but since that seems impossible based on Ryan's email from this morning, I want to make sure there's some way to get operating support from the Support Us page.

**Comment by ghwood** [comment]
ok. closing this issue as it is now set up and working.
