### ISSUE TITLE
Text in bottom section of Endowment Page is wrong

### ISSUE THREAD

**Issue by LeeBerkeleyShaw** [ghwood/www.ietf.org_content#17]
The old text from the Endowment page somehow made it onto the new page towards the bottom. 

This is the old text:

As part of its strategy to ensure the long-term future of the IETF, the IETF LLC maintains the IETF Endowment. This is a donor-restricted fund with published rules on how it is managed and how the fund is used, with the capital invested in line with the IETF LLC Investment Policy Statement.

The organizations below have made significant multi-year commitments to the IETF Endowment while multiple individuals have provided personal donations.

Now is a great time to donate to the IETF Endowment as the Internet Society has made a matching pledge with a 2-for-1 match on the first $12 million raised and 1-for-1 match on the next $6 million, which could see us raise an additional $30 million for the IETF Endowment.

Our initial goal is to raise a total of $50m by the end of 2027.

To make a donation to the IETF Endowment please use our online donation form or contact the IETF Executive Director.

The new text is:
Make an Impact Today!
Now is a great time to donate to the IETF Endowment, as the Internet Society (ISOC) has made a matching pledge with a 2-for-1 match on the first $12 million raised and a 1-for-1 match on the next $6 million, which could see us raise an additional $30 million for the IETF Endowment. Our goal is to raise $50M by 2027. As of 2021, we have raised just over $3.4M. We need your help to close that gap! Act before the match expires and your gift will have double the impact!

**Comment by LeeBerkeleyShaw** [comment]
Update: The new text is in there, below the old text. So just delete the old text. Right now, it's super repetitive.

**Comment by ghwood** [comment]
fixed: deleted stray text block. https://www7.ietf.org/endowment/
